# Aula 1.1 - Visualização de Dados - DELL Lead/UECE

In [9]:
import pandas as pd

# Função Series tabula uma lista numérica em índices

s = pd.Series([10,20,30,40,50])

print(s)

# Função values retorna uma array a uma variável a lista que foi tabulada antes

r = s.values

print(r)

print(r[2])

0    10
1    20
2    30
3    40
4    50
dtype: int64
[10 20 30 40 50]
30

In [22]:
import pandas as pd

# Exemplo 1:

ss = pd.Series([15,20,12,16,10,11,12,15,9,10,12,17], index = ['jan','fev','mar','abr','mai','jun','jul','ago','set','out','nov','dez'])
print(ss)
## Seleção de um dado de acordo com o index
print()
print('mês selecionado: ',ss['jun'])
## Seleção dos seis primeiros meses dos dados
print()
print(ss[0:6])
## Função para média da lista 'ss' tabulada
print()
media = ss.mean()
print(media)
## Função para determinar o desvio padrão da lista 'ss' tabulada
print()
dp = ss.std()
print(dp)
## Função para determinar o valor máximo e mínimo da lista 'ss' tabulada
print()
print(ss.max())
print(ss.min())
## Para determinar todas as estatísticas de uma só vez, use a função .describe()
print()
print(ss.describe())
## Para determinar o somatório dos acidentes ao longo dos meses, use a função .sum()
print()
print(ss.sum())
## Para determinar a média dos últimos seis meses da lista 'ss' tabulada
print()
print((ss[6:]).mean())

jan    15
fev    20
mar    12
abr    16
mai    10
jun    11
jul    12
ago    15
set     9
out    10
nov    12
dez    17
dtype: int64

mês selecionado:  11

jan    15
fev    20
mar    12
abr    16
mai    10
jun    11
dtype: int64

13.25

3.333712099692528

20
9

count    12.000000
mean     13.250000
std       3.333712
min       9.000000
25%      10.750000
50%      12.000000
75%      15.250000
max      20.000000
dtype: float64

159

12.5

In [9]:
import pandas as pd

# Tabulação de um dicionãrio por meio da função pd.DataFrame()
dataFrame = pd.DataFrame({'Aluno' : ['Marina','Felipe','Cleyton','Isabel'], 'Créditos cursados': [20,64,32,24], 'Rendimento acadêmico' : [8.55,7.88,8.17,9.04], 
                        'Mês de nascimento' : ['Novembro','Setembro','Janeiro','Julho'], 'Curso': ['Computação','Estatística','Computação','Matemática']})
print(dataFrame)

# Acessando aos dados de um aluno pelo index do Data Frame, usando a função .iloc[]
print()
print(dataFrame.iloc[2]) 

# Lembre que quando selecionamos uma variável do Data Frame, ela retorna uma Series, sendo possível utilizar as finções da Series
print()
rend = dataFrame['Rendimento acadêmico'].values
print(rend)
print(rend.mean())
print(rend.std())

# É possivel usar a função .describe() na Data Frame toda, apenas nas variáveis quantitativas
print()
print(dataFrame.describe())

#

     Aluno  Créditos cursados  Rendimento acadêmico Mês de nascimento  \
0   Marina                 20                  8.55          Novembro
1   Felipe                 64                  7.88          Setembro
2  Cleyton                 32                  8.17           Janeiro
3   Isabel                 24                  9.04             Julho

         Curso
0   Computação
1  Estatística
2   Computação
3   Matemática

Aluno                      Cleyton
Créditos cursados               32
Rendimento acadêmico          8.17
Mês de nascimento          Janeiro
Curso                   Computação
Name: 2, dtype: object

[8.55 7.88 8.17 9.04]
8.41
0.43445367992456896

       Créditos cursados  Rendimento acadêmico
count           4.000000              4.000000
mean           35.000000              8.410000
std            19.966639              0.501664
min            20.000000              7.880000
25%            23.000000              8.097500
50%            28.000000              8.360000
75%            40.000000              8.672500
max            64.000000              9.040000

In [25]:
import pandas as pd

# Leitura de dados via Data Frame a partir de dados existentes na internet (ou localmente)
df = pd.read_csv('https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv')
## É possível fazer a leitura do arquivo csv direto pelo PC, desde que o arquivo esteja na mesma pasta
## df=pd.read_csv('drinks.csv')
print(df)

# A função .head(number) permite a exibição de uma parte da tabela, uma vez que ela é grande
print()
print(df.head(6)) # as seis primeiras linhas
print()
print(df.head(2)) # as duas primeiras linhas

# Indexação booleana da Data Frame a partir de certos parâmetros
print()
print(df[df['country'] == 'Brazil']) # Seleciona apenas os dados que contenham a coluna 'country' para o parâmetro 'Brazil'
print()
print(df[df['total_litres_of_pure_alcohol'] >= 12]) # Seleciona apenas os dados em que a coluna 'total_litres_of_pure_alcohol' é maior que 12

# Função .sort_values(by='parâmetro', ascending = False) permite o ordenamento da Data Frame a partir de uma coluna especifica em ordens determinadas
# by --> coluna parâmetro / ascending --> True (menor para maior), False(maior para menor)
# É possível usar a função .head() para exibir os cinco primeiros resultados ou .head(numero) para quaisquer resultados
print()
print(df.sort_values(by='wine_servings', ascending = False).head())

         country  beer_servings  spirit_servings  wine_servings  \
0    Afghanistan              0                0              0
1        Albania             89              132             54
2        Algeria             25                0             14
3        Andorra            245              138            312
4         Angola            217               57             45
..           ...            ...              ...            ...
188    Venezuela            333              100              3
189      Vietnam            111                2              1
190        Yemen              6                0              0
191       Zambia             32               19              4
192     Zimbabwe             64               18              4

     total_litres_of_pure_alcohol
0                             0.0
1                             4.9
2                             0.7
3                            12.4
4                             5.9
..                            ...
188                           7.7
189                           2.0
190                           0.1
191                           2.5
192                           4.7

[193 rows x 5 columns]

             country  beer_servings  spirit_servings  wine_servings  \
0        Afghanistan              0                0              0
1            Albania             89              132             54
2            Algeria             25                0             14
3            Andorra            245              138            312
4             Angola            217               57             45
5  Antigua & Barbuda            102              128             45

   total_litres_of_pure_alcohol
0                           0.0
1                           4.9
2                           0.7
3                          12.4
4                           5.9
5                           4.9

       country  beer_servings  spirit_servings  wine_servings  \
0  Afghanistan              0                0              0
1      Albania             89              132             54

   total_litres_of_pure_alcohol
0                           0.0
1                           4.9

   country  beer_servings  spirit_servings  wine_servings  \
23  Brazil            245              145             16

    total_litres_of_pure_alcohol
23                           7.2

      country  beer_servings  spirit_servings  wine_servings  \
3     Andorra            245              138            312
15    Belarus            142              373             42
98  Lithuania            343              244             56

    total_litres_of_pure_alcohol
3                           12.4
15                          14.4
98                          12.9

         country  beer_servings  spirit_servings  wine_servings  \
61        France            127              151            370
136     Portugal            194               67            339
3        Andorra            245              138            312
166  Switzerland            185              100            280
48       Denmark            224               81            278

     total_litres_of_pure_alcohol
61                           11.8
136                          11.0
3                            12.4
166                          10.2
48                           10.4